---
title: "Lab Book"
author: "Maddi Cummins"
output: html_document
---

##Progress Over Break

###Data

#####Tables

* Finished writing calculations for per million table and pushed to github (using MM's Pop.Rdata and Fatal Encounters through rio)
* Using the "DT" package I created a function to create a data table from per mill. The function takes in two inputs: state and all. State determines which state is displayed or highlighted. All is a boolean which if TRUE the data table contains all the states and the selected state is highlighted, if FALSE the data table is of length 1 and only includes the selected state.

#####Graphics

* I created a function to make a graph of time vs kills per million. The function takes in two inputs: state and all. State determines which state is displayed or highlighted. All is a boolean which if TRUE the data table contains all the states and the selected state is highlighted red and US is highlighted black with a legend, if FALSE the graph is just of the data for the selected state.

###ShinyApp

* Created a first draft for the UI of the ShinyApp. Space is optimized by using tabs.
* Added Graph and Data table to "Per Capita" tab so that they are interactable with the select and checkbox inputs. Used functions created in Data folder to create visuals.

##Week 1

###Data

#####Capita

* added a "capita" argument to "permillcalculation.R", "permillgraph.R", and "permilltable.R". This variable toggles whether the data is evaluated by population or just by counts. 
* permillgraph and permilltable functions both call permillcalc function with capita set to egual the passed in capita. 
* Capita also changes some other features (whether to graph US total etc.).

###ShinyApp

#####UI

* Created a togle button that interacts with the capita variable so that users can choose whether they want to see total or by capita results. - Set to "TRUE"

#####Error

* Table has appeared to stop rendering in shiny app. However, it does render when permilltable function is called.
* Currently working on fixes...