---
title: "linker Report"
output:
  html_document:
    code_folding: hide
---

```{r, include= FALSE}
library(DataExplorer)
library(networkD3)
library(dplyr)
library(rlist)

path_to_src = here::here(file.path( 'Data'))
load(file=file.path(path_to_src,
                    "FinalClassification",
                    "full_classification.RData"))

load(file=file.path(path_to_src,
                    "FinalClassification",
                    "full_combined_harmonized.RData"))

load(file= file.path(path_to_src,
                     "HarmonizedFiles",
                     "HarmonizedDataSets.RData"))
```


## Overview

Common columns :
```{r}
Reduce(intersect, list(colnames(kbp_harmonized),
                                     colnames(fe_harmonized),
                                     colnames(mpv_harmonized),
                                     colnames(wapo_harmonized)))
```


Classification outputs:

Classification is a list of 10 components:
```{r}
list.names(classification)
```

* Data:
```{r}
str <- plot_str(classification$data,
                print_network = FALSE)
diagonalNetwork(str)
```

* Pairs:
```{r}
str <- plot_str(classification$pairs,
                print_network = FALSE)
diagonalNetwork(str)

```


* Frequencies:
```{r}
classification$frequencies
```

* type 
```{r}
classification$type
```

* M:
```{r}
head(classification$M)
```

* W:
```{r}
head(classification$W)
```


* U :
```{r}
head(classification$U)
```


* Wdata:
```{r}
head(classification$Wdata)
```


* Prediction:

```{r}
table(classification$prediction)
```
### Missing data 

```{r}
plot_missing(classification$data)
```



Combined harmonized outputs:

```{r}
str <- plot_str(combined_harmonized,
                print_network = FALSE)
diagonalNetwork(str)

```

### Missing data
```{r}

common <-  combined_harmonized %>% 
            select(firstname,
                       lastname,
                       age,
                       sex,
                       race,
                       state,
                       year)
plot_missing(common)
```

